version: '3.8'

services:
  mc-web-console-api:
    container_name: mc-web-console-api

    image: mc-web-console-api:latest
    # sudo docker build -f ./api/Dockerfile.mcwebconsoleapi -t mc-web-console-api:latest .

    # build:
    #   context: ../
    #   dockerfile: api/Dockerfile.mcwebconsoleapi
    networks:
      - mc-web-console-network
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
    depends_on:
      - mc-web-console-db
    environment:
      DATABASE_URL: postgres://${WEBCONSOLE_POSTGRES_USER}:${WEBCONSOLE_POSTGRES_PASSWORD}@mc-web-console-db:5432/${WEBCONSOLE_POSTGRES_DB}
      MCIAM_USE: "true"
      MCIAM_TICKET_USE: "false"
      API_ADDR: 0.0.0.0
      API_PORT: 3000
    volumes:
      - ./container-volume/mc-web-console-api/conf:/conf
    env_file:
      - .env

  mc-web-console-front:
    container_name: mc-web-console-front

    image: mc-web-console-front:latest
    # sudo docker build -f ./front/Dockerfile.mcwebconsolefront -t mc-web-console-front:latest .

    # build:
    #   context: ../
    #   dockerfile: front/Dockerfile.mcwebconsolefront
    networks:
      - mc-web-console-network
    ports:
      - target: 3001
        published: 3001
        protocol: tcp
    depends_on:
      - mc-web-console-db
      - mc-web-console-api
    environment:
      API_ADDR: mc-web-console-api
      API_PORT: 3000
      FRONT_ADDR: 0.0.0.0
      FRONT_PORT: 3001

  mc-web-console-db:
    container_name: mc-web-console-db
    image: postgres:14-alpine
    networks:
      - mc-web-console-network
    # ports:
    #   - target: 5432
    #     published: 5432
    #     protocol: tcp
    env_file:
      - .env
    volumes:
      - ./container-volume/mc-web-console/postgres/postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${WEBCONSOLE_POSTGRES_DB}
      POSTGRES_USER: ${WEBCONSOLE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${WEBCONSOLE_POSTGRES_PASSWORD}

networks:
  mc-web-console-network:
