root = "."
tmp_dir = "tmp"
[build]
  cmd = "go build -o ./tmp/main main.go"
  bin = "./tmp/main"
  full_bin = ""
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]

[log]
  level = "info"

[watch]
  include = ["."]
  exclude = ["tmp", "vendor"]
  extensions = ["go"]
  delay = 1000